name: Tauri Build
on:
  push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            label: windows
          - os: macos-latest
            label: macos-universal
          - os: macos-latest
            label: macos-intel
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Rust x86_64 target (macOS-intel only)
        if: matrix.os == 'macos-latest'
        run: rustup target add x86_64-apple-darwin

      - name: Install dependencies (pnpm)
        run: pnpm install

      - name: Tauri build (macOS Universal)
        if: matrix.label == 'macos-universal'
        run: pnpm run tauri build --target universal-apple-darwin

      - name: Upload artifacts
        if: success() && matrix.label == 'macos-universal'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundle-${{ matrix.label }}
          path: src-tauri/target/universal-apple-darwin/release/bundle/

      - name: Tauri build (macOS Intel)
        if: matrix.label == 'macos-intel'
        run: pnpm run tauri build --target x86_64-apple-darwin

      - name: Upload artifacts
        if: success() && matrix.label == 'macos-intel'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundle-${{ matrix.label }}
          path: src-tauri/target/x86_64-apple-darwin/release/bundle/

      - name: Tauri build (Windows)
        if: matrix.label == 'windows'
        run: pnpm run tauri build

      - name: Upload artifacts
        if: success() && matrix.label == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundle-${{ matrix.label }}
          path: src-tauri/target/release/bundle/
